services:
  btcpp_ros2_example:
    image: btcpp_ros2
    container_name: btcpp_ros2_example
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./ros2_ws:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - WEBOTS_GATEWAY=${WEBOTS_GATEWAY}
    command: ["bash"]

    build:
      context: .
      dockerfile: Dockerfile

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    expose:
      - "11311"
      - "12345"
      - "22"
      - "5555"
